# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/spi_master_xdc.xdc

# Block Designs: bd/spi/spi.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi || ORIG_REF_NAME==spi} -quiet] -quiet

# IP: bd/spi/ip/spi_microblaze_0_2/spi_microblaze_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_microblaze_0_2 || ORIG_REF_NAME==spi_microblaze_0_2} -quiet] -quiet

# IP: bd/spi/ip/spi_axi_quad_spi_0_2/spi_axi_quad_spi_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_axi_quad_spi_0_2 || ORIG_REF_NAME==spi_axi_quad_spi_0_2} -quiet] -quiet

# IP: bd/spi/ip/spi_axi_uartlite_0_1/spi_axi_uartlite_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_axi_uartlite_0_1 || ORIG_REF_NAME==spi_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/spi/ip/spi_dlmb_v10_2/spi_dlmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_dlmb_v10_2 || ORIG_REF_NAME==spi_dlmb_v10_2} -quiet] -quiet

# IP: bd/spi/ip/spi_ilmb_v10_2/spi_ilmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_ilmb_v10_2 || ORIG_REF_NAME==spi_ilmb_v10_2} -quiet] -quiet

# IP: bd/spi/ip/spi_dlmb_bram_if_cntlr_2/spi_dlmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==spi_dlmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/spi/ip/spi_ilmb_bram_if_cntlr_2/spi_ilmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==spi_ilmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/spi/ip/spi_lmb_bram_2/spi_lmb_bram_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_lmb_bram_2 || ORIG_REF_NAME==spi_lmb_bram_2} -quiet] -quiet

# IP: bd/spi/ip/spi_mdm_1_2/spi_mdm_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_mdm_1_2 || ORIG_REF_NAME==spi_mdm_1_2} -quiet] -quiet

# IP: bd/spi/ip/spi_clk_wiz_1_2/spi_clk_wiz_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_clk_wiz_1_2 || ORIG_REF_NAME==spi_clk_wiz_1_2} -quiet] -quiet

# IP: bd/spi/ip/spi_rst_clk_wiz_1_100M_2/spi_rst_clk_wiz_1_100M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_rst_clk_wiz_1_100M_2 || ORIG_REF_NAME==spi_rst_clk_wiz_1_100M_2} -quiet] -quiet

# IP: bd/spi/ip/spi_xbar_1/spi_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_xbar_1 || ORIG_REF_NAME==spi_xbar_1} -quiet] -quiet

# IP: bd/spi/ip/spi_microblaze_0_axi_periph_6/spi_microblaze_0_axi_periph_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_microblaze_0_axi_periph_6 || ORIG_REF_NAME==spi_microblaze_0_axi_periph_6} -quiet] -quiet

# XDC: d:/vivado_pj/spi_master_ip/spi_master_ip.gen/sources_1/bd/spi/spi_ooc.xdc
