# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/lcd_test_xdc.xdc

# Block Designs: bd/lcd_test/lcd_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_test || ORIG_REF_NAME==lcd_test} -quiet] -quiet

# IP: bd/lcd_test/ip/lcd_test_microblaze_0_0/lcd_test_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_test_microblaze_0_0 || ORIG_REF_NAME==lcd_test_microblaze_0_0} -quiet] -quiet

# IP: bd/lcd_test/ip/lcd_test_axi_uartlite_0_0/lcd_test_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_test_axi_uartlite_0_0 || ORIG_REF_NAME==lcd_test_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/lcd_test/ip/lcd_test_lcd_axi_v1_0_0_0/lcd_test_lcd_axi_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_test_lcd_axi_v1_0_0_0 || ORIG_REF_NAME==lcd_test_lcd_axi_v1_0_0_0} -quiet] -quiet

# IP: bd/lcd_test/ip/lcd_test_rtc_axi_v1_0_0_0/lcd_test_rtc_axi_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_test_rtc_axi_v1_0_0_0 || ORIG_REF_NAME==lcd_test_rtc_axi_v1_0_0_0} -quiet] -quiet

# IP: bd/lcd_test/ip/lcd_test_dlmb_v10_0/lcd_test_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_test_dlmb_v10_0 || ORIG_REF_NAME==lcd_test_dlmb_v10_0} -quiet] -quiet

# IP: bd/lcd_test/ip/lcd_test_ilmb_v10_0/lcd_test_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_test_ilmb_v10_0 || ORIG_REF_NAME==lcd_test_ilmb_v10_0} -quiet] -quiet

# IP: bd/lcd_test/ip/lcd_test_dlmb_bram_if_cntlr_0/lcd_test_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_test_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==lcd_test_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/lcd_test/ip/lcd_test_ilmb_bram_if_cntlr_0/lcd_test_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_test_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==lcd_test_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/lcd_test/ip/lcd_test_lmb_bram_0/lcd_test_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_test_lmb_bram_0 || ORIG_REF_NAME==lcd_test_lmb_bram_0} -quiet] -quiet

# IP: bd/lcd_test/ip/lcd_test_mdm_1_0/lcd_test_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_test_mdm_1_0 || ORIG_REF_NAME==lcd_test_mdm_1_0} -quiet] -quiet

# IP: bd/lcd_test/ip/lcd_test_clk_wiz_1_0/lcd_test_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_test_clk_wiz_1_0 || ORIG_REF_NAME==lcd_test_clk_wiz_1_0} -quiet] -quiet

# IP: bd/lcd_test/ip/lcd_test_rst_clk_wiz_1_100M_0/lcd_test_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_test_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==lcd_test_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/lcd_test/ip/lcd_test_xbar_0/lcd_test_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_test_xbar_0 || ORIG_REF_NAME==lcd_test_xbar_0} -quiet] -quiet

# IP: bd/lcd_test/ip/lcd_test_microblaze_0_axi_periph_0/lcd_test_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_test_microblaze_0_axi_periph_0 || ORIG_REF_NAME==lcd_test_microblaze_0_axi_periph_0} -quiet] -quiet

# XDC: d:/vivado_pj/text_lcd_ip_pj/text_lcd_ip_pj.gen/sources_1/bd/lcd_test/lcd_test_ooc.xdc
