# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/AIOT/vivado_pj/block_memory_pj/block_memory_pj.srcs/sources_1/ip/spram1/spram1.xci
# IP: The module: 'spram1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/AIOT/vivado_pj/block_memory_pj/block_memory_pj.gen/sources_1/ip/spram1/spram1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spram1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/AIOT/vivado_pj/block_memory_pj/block_memory_pj.srcs/sources_1/ip/spram1/spram1.xci
# IP: The module: 'spram1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/AIOT/vivado_pj/block_memory_pj/block_memory_pj.gen/sources_1/ip/spram1/spram1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spram1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
