# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/vivado_pj/vga_controller_ip/vga_controller_ip.srcs/sources_1/bd/vga_test/ip/vga_test_rst_clk_wiz_100M_0/vga_test_rst_clk_wiz_100M_0.xci
# IP: The module: 'vga_test_rst_clk_wiz_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/vivado_pj/vga_controller_ip/vga_controller_ip.gen/sources_1/bd/vga_test/ip/vga_test_rst_clk_wiz_100M_0/vga_test_rst_clk_wiz_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_test_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/vivado_pj/vga_controller_ip/vga_controller_ip.gen/sources_1/bd/vga_test/ip/vga_test_rst_clk_wiz_100M_0/vga_test_rst_clk_wiz_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_test_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/vivado_pj/vga_controller_ip/vga_controller_ip.gen/sources_1/bd/vga_test/ip/vga_test_rst_clk_wiz_100M_0/vga_test_rst_clk_wiz_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_test_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/vivado_pj/vga_controller_ip/vga_controller_ip.srcs/sources_1/bd/vga_test/ip/vga_test_rst_clk_wiz_100M_0/vga_test_rst_clk_wiz_100M_0.xci
# IP: The module: 'vga_test_rst_clk_wiz_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/vivado_pj/vga_controller_ip/vga_controller_ip.gen/sources_1/bd/vga_test/ip/vga_test_rst_clk_wiz_100M_0/vga_test_rst_clk_wiz_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_test_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/vivado_pj/vga_controller_ip/vga_controller_ip.gen/sources_1/bd/vga_test/ip/vga_test_rst_clk_wiz_100M_0/vga_test_rst_clk_wiz_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_test_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/vivado_pj/vga_controller_ip/vga_controller_ip.gen/sources_1/bd/vga_test/ip/vga_test_rst_clk_wiz_100M_0/vga_test_rst_clk_wiz_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_test_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
