# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/pwm_control_ip/pwm_control_ip.srcs/sources_1/bd/pwm_test/ip/pwm_test_clk_wiz_1_1/pwm_test_clk_wiz_1_1.xci
# IP: The module: 'pwm_test_clk_wiz_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/pwm_control_ip/pwm_control_ip.gen/sources_1/bd/pwm_test/ip/pwm_test_clk_wiz_1_1/pwm_test_clk_wiz_1_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pwm_test_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: h:/pwm_control_ip/pwm_control_ip.gen/sources_1/bd/pwm_test/ip/pwm_test_clk_wiz_1_1/pwm_test_clk_wiz_1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'pwm_test_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: h:/pwm_control_ip/pwm_control_ip.gen/sources_1/bd/pwm_test/ip/pwm_test_clk_wiz_1_1/pwm_test_clk_wiz_1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pwm_test_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: h:/pwm_control_ip/pwm_control_ip.srcs/sources_1/bd/pwm_test/ip/pwm_test_clk_wiz_1_1/pwm_test_clk_wiz_1_1.xci
# IP: The module: 'pwm_test_clk_wiz_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/pwm_control_ip/pwm_control_ip.gen/sources_1/bd/pwm_test/ip/pwm_test_clk_wiz_1_1/pwm_test_clk_wiz_1_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pwm_test_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: h:/pwm_control_ip/pwm_control_ip.gen/sources_1/bd/pwm_test/ip/pwm_test_clk_wiz_1_1/pwm_test_clk_wiz_1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'pwm_test_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: h:/pwm_control_ip/pwm_control_ip.gen/sources_1/bd/pwm_test/ip/pwm_test_clk_wiz_1_1/pwm_test_clk_wiz_1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pwm_test_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
