# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/vga_test_xdc.xdc

# Block Designs: bd/vga_test/vga_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vga_test || ORIG_REF_NAME==vga_test} -quiet] -quiet

# IP: bd/vga_test/ip/vga_test_top_0_0/vga_test_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vga_test_top_0_0 || ORIG_REF_NAME==vga_test_top_0_0} -quiet] -quiet

# IP: bd/vga_test/ip/vga_test_clk_wiz_0/vga_test_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vga_test_clk_wiz_0 || ORIG_REF_NAME==vga_test_clk_wiz_0} -quiet] -quiet

# IP: bd/vga_test/ip/vga_test_rst_clk_wiz_100M_0/vga_test_rst_clk_wiz_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vga_test_rst_clk_wiz_100M_0 || ORIG_REF_NAME==vga_test_rst_clk_wiz_100M_0} -quiet] -quiet

# XDC: c:/vivado_pj/vga_controller_ip/vga_controller_ip.gen/sources_1/bd/vga_test/vga_test_ooc.xdc
