# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/mb1_block.xdc

# Block Designs: bd/mb1_block/mb1_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_block || ORIG_REF_NAME==mb1_block} -quiet] -quiet

# IP: bd/mb1_block/ip/mb1_block_microblaze_0_0/mb1_block_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_block_microblaze_0_0 || ORIG_REF_NAME==mb1_block_microblaze_0_0} -quiet] -quiet

# IP: bd/mb1_block/ip/mb1_block_dlmb_v10_0/mb1_block_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_block_dlmb_v10_0 || ORIG_REF_NAME==mb1_block_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb1_block/ip/mb1_block_ilmb_v10_0/mb1_block_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_block_ilmb_v10_0 || ORIG_REF_NAME==mb1_block_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb1_block/ip/mb1_block_dlmb_bram_if_cntlr_0/mb1_block_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_block_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb1_block_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb1_block/ip/mb1_block_ilmb_bram_if_cntlr_0/mb1_block_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_block_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb1_block_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb1_block/ip/mb1_block_lmb_bram_0/mb1_block_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_block_lmb_bram_0 || ORIG_REF_NAME==mb1_block_lmb_bram_0} -quiet] -quiet

# IP: bd/mb1_block/ip/mb1_block_xbar_0/mb1_block_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_block_xbar_0 || ORIG_REF_NAME==mb1_block_xbar_0} -quiet] -quiet

# IP: bd/mb1_block/ip/mb1_block_microblaze_0_axi_periph_0/mb1_block_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_block_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb1_block_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb1_block/ip/mb1_block_microblaze_0_axi_intc_0/mb1_block_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_block_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb1_block_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb1_block/ip/mb1_block_microblaze_0_xlconcat_0/mb1_block_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_block_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mb1_block_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mb1_block/ip/mb1_block_mdm_1_0/mb1_block_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_block_mdm_1_0 || ORIG_REF_NAME==mb1_block_mdm_1_0} -quiet] -quiet

# IP: bd/mb1_block/ip/mb1_block_clk_wiz_1_0/mb1_block_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_block_clk_wiz_1_0 || ORIG_REF_NAME==mb1_block_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb1_block/ip/mb1_block_rst_clk_wiz_1_100M_0/mb1_block_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_block_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb1_block_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mb1_block/ip/mb1_block_axi_timer_0_0/mb1_block_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_block_axi_timer_0_0 || ORIG_REF_NAME==mb1_block_axi_timer_0_0} -quiet] -quiet

# IP: bd/mb1_block/ip/mb1_block_axi_uartlite_0_0/mb1_block_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_block_axi_uartlite_0_0 || ORIG_REF_NAME==mb1_block_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb1_block/ip/mb1_block_axi_gpio_1_4/mb1_block_axi_gpio_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_block_axi_gpio_1_4 || ORIG_REF_NAME==mb1_block_axi_gpio_1_4} -quiet] -quiet

# IP: bd/mb1_block/ip/mb1_block_axi_gpio_2_1/mb1_block_axi_gpio_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_block_axi_gpio_2_1 || ORIG_REF_NAME==mb1_block_axi_gpio_2_1} -quiet] -quiet

# IP: bd/mb1_block/ip/mb1_block_axi_gpio_3_1/mb1_block_axi_gpio_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_block_axi_gpio_3_1 || ORIG_REF_NAME==mb1_block_axi_gpio_3_1} -quiet] -quiet

# IP: bd/mb1_block/ip/mb1_block_axi_gpio_0_1/mb1_block_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_block_axi_gpio_0_1 || ORIG_REF_NAME==mb1_block_axi_gpio_0_1} -quiet] -quiet

# XDC: d:/vivado_pj/project_mb1/project_mb1.gen/sources_1/bd/mb1_block/mb1_block_ooc.xdc
