# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/fnd_xdc.xdc

# Block Designs: bd/axi_fnd/axi_fnd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_fnd || ORIG_REF_NAME==axi_fnd} -quiet] -quiet

# IP: bd/axi_fnd/ip/axi_fnd_microblaze_0_0/axi_fnd_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_fnd_microblaze_0_0 || ORIG_REF_NAME==axi_fnd_microblaze_0_0} -quiet] -quiet

# IP: bd/axi_fnd/ip/axi_fnd_axi_uartlite_0_0/axi_fnd_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_fnd_axi_uartlite_0_0 || ORIG_REF_NAME==axi_fnd_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/axi_fnd/ip/axi_fnd_dlmb_v10_0/axi_fnd_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_fnd_dlmb_v10_0 || ORIG_REF_NAME==axi_fnd_dlmb_v10_0} -quiet] -quiet

# IP: bd/axi_fnd/ip/axi_fnd_ilmb_v10_0/axi_fnd_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_fnd_ilmb_v10_0 || ORIG_REF_NAME==axi_fnd_ilmb_v10_0} -quiet] -quiet

# IP: bd/axi_fnd/ip/axi_fnd_dlmb_bram_if_cntlr_0/axi_fnd_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_fnd_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==axi_fnd_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/axi_fnd/ip/axi_fnd_ilmb_bram_if_cntlr_0/axi_fnd_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_fnd_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==axi_fnd_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/axi_fnd/ip/axi_fnd_lmb_bram_0/axi_fnd_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_fnd_lmb_bram_0 || ORIG_REF_NAME==axi_fnd_lmb_bram_0} -quiet] -quiet

# IP: bd/axi_fnd/ip/axi_fnd_mdm_1_0/axi_fnd_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_fnd_mdm_1_0 || ORIG_REF_NAME==axi_fnd_mdm_1_0} -quiet] -quiet

# IP: bd/axi_fnd/ip/axi_fnd_clk_wiz_1_0/axi_fnd_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_fnd_clk_wiz_1_0 || ORIG_REF_NAME==axi_fnd_clk_wiz_1_0} -quiet] -quiet

# IP: bd/axi_fnd/ip/axi_fnd_rst_clk_wiz_1_100M_0/axi_fnd_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_fnd_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==axi_fnd_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/axi_fnd/ip/axi_fnd_xbar_0/axi_fnd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_fnd_xbar_0 || ORIG_REF_NAME==axi_fnd_xbar_0} -quiet] -quiet

# IP: bd/axi_fnd/ip/axi_fnd_microblaze_0_axi_periph_0/axi_fnd_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_fnd_microblaze_0_axi_periph_0 || ORIG_REF_NAME==axi_fnd_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/axi_fnd/ip/axi_fnd_axi_fnd_v1_0_0_4/axi_fnd_axi_fnd_v1_0_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_fnd_axi_fnd_v1_0_0_4 || ORIG_REF_NAME==axi_fnd_axi_fnd_v1_0_0_4} -quiet] -quiet

# XDC: d:/vivado_pj/my_ip_fnd/my_ip_fnd.gen/sources_1/bd/axi_fnd/axi_fnd_ooc.xdc
