# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/vivado_pj/vga_controller_pj/vga_controller_pj.srcs/sources_1/ip/image_rom/image_rom.xci
# IP: The module: 'image_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/vivado_pj/vga_controller_pj/vga_controller_pj.gen/sources_1/ip/image_rom/image_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/vivado_pj/vga_controller_pj/vga_controller_pj.srcs/sources_1/ip/image_rom/image_rom.xci
# IP: The module: 'image_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/vivado_pj/vga_controller_pj/vga_controller_pj.gen/sources_1/ip/image_rom/image_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
