# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/vivado_pj/blaze_w5500/blaze_w5500.srcs/sources_1/bd/system/ip/system_axi_gpio_0_3/system_axi_gpio_0_3.xci
# IP: The module: 'system_axi_gpio_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_pj/blaze_w5500/blaze_w5500.gen/sources_1/bd/system/ip/system_axi_gpio_0_3/system_axi_gpio_0_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/vivado_pj/blaze_w5500/blaze_w5500.gen/sources_1/bd/system/ip/system_axi_gpio_0_3/system_axi_gpio_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/vivado_pj/blaze_w5500/blaze_w5500.gen/sources_1/bd/system/ip/system_axi_gpio_0_3/system_axi_gpio_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/vivado_pj/blaze_w5500/blaze_w5500.srcs/sources_1/bd/system/ip/system_axi_gpio_0_3/system_axi_gpio_0_3.xci
# IP: The module: 'system_axi_gpio_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_pj/blaze_w5500/blaze_w5500.gen/sources_1/bd/system/ip/system_axi_gpio_0_3/system_axi_gpio_0_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/vivado_pj/blaze_w5500/blaze_w5500.gen/sources_1/bd/system/ip/system_axi_gpio_0_3/system_axi_gpio_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/vivado_pj/blaze_w5500/blaze_w5500.gen/sources_1/bd/system/ip/system_axi_gpio_0_3/system_axi_gpio_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
