# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/vivado_pj/RTC_FND_AXI/RTC_FND_AXI.srcs/sources_1/bd/rtc_fnd_axi/ip/rtc_fnd_axi_clk_wiz_1_2/rtc_fnd_axi_clk_wiz_1_2.xci
# IP: The module: 'rtc_fnd_axi_clk_wiz_1_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_pj/RTC_FND_AXI/RTC_FND_AXI.gen/sources_1/bd/rtc_fnd_axi/ip/rtc_fnd_axi_clk_wiz_1_2/rtc_fnd_axi_clk_wiz_1_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'rtc_fnd_axi_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/vivado_pj/RTC_FND_AXI/RTC_FND_AXI.gen/sources_1/bd/rtc_fnd_axi/ip/rtc_fnd_axi_clk_wiz_1_2/rtc_fnd_axi_clk_wiz_1_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'rtc_fnd_axi_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/vivado_pj/RTC_FND_AXI/RTC_FND_AXI.gen/sources_1/bd/rtc_fnd_axi/ip/rtc_fnd_axi_clk_wiz_1_2/rtc_fnd_axi_clk_wiz_1_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rtc_fnd_axi_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/vivado_pj/RTC_FND_AXI/RTC_FND_AXI.srcs/sources_1/bd/rtc_fnd_axi/ip/rtc_fnd_axi_clk_wiz_1_2/rtc_fnd_axi_clk_wiz_1_2.xci
# IP: The module: 'rtc_fnd_axi_clk_wiz_1_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_pj/RTC_FND_AXI/RTC_FND_AXI.gen/sources_1/bd/rtc_fnd_axi/ip/rtc_fnd_axi_clk_wiz_1_2/rtc_fnd_axi_clk_wiz_1_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'rtc_fnd_axi_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/vivado_pj/RTC_FND_AXI/RTC_FND_AXI.gen/sources_1/bd/rtc_fnd_axi/ip/rtc_fnd_axi_clk_wiz_1_2/rtc_fnd_axi_clk_wiz_1_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'rtc_fnd_axi_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/vivado_pj/RTC_FND_AXI/RTC_FND_AXI.gen/sources_1/bd/rtc_fnd_axi/ip/rtc_fnd_axi_clk_wiz_1_2/rtc_fnd_axi_clk_wiz_1_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rtc_fnd_axi_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
