# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/bramXdc.xdc

# Block Designs: bd/system1/system1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system1 || ORIG_REF_NAME==system1} -quiet] -quiet

# IP: bd/system1/ip/system1_microblaze_0_0/system1_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system1_microblaze_0_0 || ORIG_REF_NAME==system1_microblaze_0_0} -quiet] -quiet

# IP: bd/system1/ip/system1_dlmb_v10_0/system1_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system1_dlmb_v10_0 || ORIG_REF_NAME==system1_dlmb_v10_0} -quiet] -quiet

# IP: bd/system1/ip/system1_ilmb_v10_0/system1_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system1_ilmb_v10_0 || ORIG_REF_NAME==system1_ilmb_v10_0} -quiet] -quiet

# IP: bd/system1/ip/system1_dlmb_bram_if_cntlr_0/system1_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==system1_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/system1/ip/system1_ilmb_bram_if_cntlr_0/system1_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==system1_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/system1/ip/system1_lmb_bram_0/system1_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system1_lmb_bram_0 || ORIG_REF_NAME==system1_lmb_bram_0} -quiet] -quiet

# IP: bd/system1/ip/system1_xbar_0/system1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system1_xbar_0 || ORIG_REF_NAME==system1_xbar_0} -quiet] -quiet

# IP: bd/system1/ip/system1_auto_pc_0/system1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system1_auto_pc_0 || ORIG_REF_NAME==system1_auto_pc_0} -quiet] -quiet

# IP: bd/system1/ip/system1_microblaze_0_axi_periph_0/system1_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==system1_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/system1/ip/system1_microblaze_0_axi_intc_0/system1_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system1_microblaze_0_axi_intc_0 || ORIG_REF_NAME==system1_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/system1/ip/system1_microblaze_0_xlconcat_0/system1_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system1_microblaze_0_xlconcat_0 || ORIG_REF_NAME==system1_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/system1/ip/system1_mdm_1_0/system1_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system1_mdm_1_0 || ORIG_REF_NAME==system1_mdm_1_0} -quiet] -quiet

# IP: bd/system1/ip/system1_clk_wiz_1_0/system1_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system1_clk_wiz_1_0 || ORIG_REF_NAME==system1_clk_wiz_1_0} -quiet] -quiet

# IP: bd/system1/ip/system1_rst_clk_wiz_1_100M_0/system1_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==system1_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/system1/ip/system1_axi_uartlite_0_1/system1_axi_uartlite_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system1_axi_uartlite_0_1 || ORIG_REF_NAME==system1_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/system1/ip/system1_axi_gpio_0_0/system1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system1_axi_gpio_0_0 || ORIG_REF_NAME==system1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/system1/ip/system1_axi_bram_ctrl_0_1/system1_axi_bram_ctrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system1_axi_bram_ctrl_0_1 || ORIG_REF_NAME==system1_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/system1/ip/system1_axi_bram_ctrl_0_bram_0/system1_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system1_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==system1_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# XDC: d:/vivado_pj/bram02/bram02.gen/sources_1/bd/system1/system1_ooc.xdc
