# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/vivado_pj/userMap/userMap.srcs/sources_1/bd/system/ip/system_clk_wiz_1_1/system_clk_wiz_1_1.xci
# IP: The module: 'system_clk_wiz_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_pj/userMap/userMap.gen/sources_1/bd/system/ip/system_clk_wiz_1_1/system_clk_wiz_1_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/vivado_pj/userMap/userMap.gen/sources_1/bd/system/ip/system_clk_wiz_1_1/system_clk_wiz_1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/vivado_pj/userMap/userMap.gen/sources_1/bd/system/ip/system_clk_wiz_1_1/system_clk_wiz_1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/vivado_pj/userMap/userMap.srcs/sources_1/bd/system/ip/system_clk_wiz_1_1/system_clk_wiz_1_1.xci
# IP: The module: 'system_clk_wiz_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_pj/userMap/userMap.gen/sources_1/bd/system/ip/system_clk_wiz_1_1/system_clk_wiz_1_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/vivado_pj/userMap/userMap.gen/sources_1/bd/system/ip/system_clk_wiz_1_1/system_clk_wiz_1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/vivado_pj/userMap/userMap.gen/sources_1/bd/system/ip/system_clk_wiz_1_1/system_clk_wiz_1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
