set_property SRC_FILE_INFO {cfile:d:/vivado_pj/project_mb_spi_2023/project_mb1.gen/sources_1/bd/mb1_block/ip/mb1_block_axi_gpio_1_4/mb1_block_axi_gpio_1_4_ooc.xdc rfile:../../../../../project_mb1.gen/sources_1/bd/mb1_block/ip/mb1_block_axi_gpio_1_4/mb1_block_axi_gpio_1_4_ooc.xdc id:1 order:EARLY scoped_inst:U0} [current_design]
set_property SRC_FILE_INFO {cfile:d:/vivado_pj/project_mb_spi_2023/project_mb1.gen/sources_1/bd/mb1_block/ip/mb1_block_axi_gpio_1_4/mb1_block_axi_gpio_1_4.xdc rfile:../../../../../project_mb1.gen/sources_1/bd/mb1_block/ip/mb1_block_axi_gpio_1_4/mb1_block_axi_gpio_1_4.xdc id:2 order:EARLY scoped_inst:U0} [current_design]
set_property SRC_FILE_INFO {cfile:D:/vivado_pj/project_mb_spi_2023/project_mb1.runs/mb1_block_axi_gpio_1_4_synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:3} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:59 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 10.000 -name s_axi_clk [get_ports s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins {U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.FOR_IN_cdc_to[0].CROSS2_PLEVEL_IN2SCNDRY_IN_cdc_to/D}]
set_property src_info {type:XDC file:3 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells U0]
