# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/vivado_pj/pwm_my_ip/pwm_my_ip.srcs/sources_1/bd/pwm_test/ip/pwm_test_lmb_bram_0/pwm_test_lmb_bram_0.xci
# IP: The module: 'pwm_test_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_pj/pwm_my_ip/pwm_my_ip.gen/sources_1/bd/pwm_test/ip/pwm_test_lmb_bram_0/pwm_test_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pwm_test_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/vivado_pj/pwm_my_ip/pwm_my_ip.srcs/sources_1/bd/pwm_test/ip/pwm_test_lmb_bram_0/pwm_test_lmb_bram_0.xci
# IP: The module: 'pwm_test_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_pj/pwm_my_ip/pwm_my_ip.gen/sources_1/bd/pwm_test/ip/pwm_test_lmb_bram_0/pwm_test_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pwm_test_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
