# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pwm_test_xdc.xdc

# Block Designs: bd/pwm_test/pwm_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_test || ORIG_REF_NAME==pwm_test} -quiet] -quiet

# IP: bd/pwm_test/ip/pwm_test_axi_uartlite_0_0/pwm_test_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_test_axi_uartlite_0_0 || ORIG_REF_NAME==pwm_test_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/pwm_test/ip/pwm_test_microblaze_0_0/pwm_test_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_test_microblaze_0_0 || ORIG_REF_NAME==pwm_test_microblaze_0_0} -quiet] -quiet

# IP: bd/pwm_test/ip/pwm_test_axi_gpio_0_0/pwm_test_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_test_axi_gpio_0_0 || ORIG_REF_NAME==pwm_test_axi_gpio_0_0} -quiet] -quiet

# IP: bd/pwm_test/ip/pwm_test_dlmb_v10_0/pwm_test_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_test_dlmb_v10_0 || ORIG_REF_NAME==pwm_test_dlmb_v10_0} -quiet] -quiet

# IP: bd/pwm_test/ip/pwm_test_ilmb_v10_0/pwm_test_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_test_ilmb_v10_0 || ORIG_REF_NAME==pwm_test_ilmb_v10_0} -quiet] -quiet

# IP: bd/pwm_test/ip/pwm_test_dlmb_bram_if_cntlr_0/pwm_test_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_test_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==pwm_test_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/pwm_test/ip/pwm_test_ilmb_bram_if_cntlr_0/pwm_test_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_test_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==pwm_test_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/pwm_test/ip/pwm_test_lmb_bram_0/pwm_test_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_test_lmb_bram_0 || ORIG_REF_NAME==pwm_test_lmb_bram_0} -quiet] -quiet

# IP: bd/pwm_test/ip/pwm_test_xbar_0/pwm_test_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_test_xbar_0 || ORIG_REF_NAME==pwm_test_xbar_0} -quiet] -quiet

# IP: bd/pwm_test/ip/pwm_test_microblaze_0_axi_periph_0/pwm_test_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_test_microblaze_0_axi_periph_0 || ORIG_REF_NAME==pwm_test_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/pwm_test/ip/pwm_test_microblaze_0_axi_intc_0/pwm_test_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_test_microblaze_0_axi_intc_0 || ORIG_REF_NAME==pwm_test_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/pwm_test/ip/pwm_test_microblaze_0_xlconcat_0/pwm_test_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_test_microblaze_0_xlconcat_0 || ORIG_REF_NAME==pwm_test_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/pwm_test/ip/pwm_test_mdm_1_0/pwm_test_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_test_mdm_1_0 || ORIG_REF_NAME==pwm_test_mdm_1_0} -quiet] -quiet

# IP: bd/pwm_test/ip/pwm_test_clk_wiz_1_0/pwm_test_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_test_clk_wiz_1_0 || ORIG_REF_NAME==pwm_test_clk_wiz_1_0} -quiet] -quiet

# IP: bd/pwm_test/ip/pwm_test_rst_clk_wiz_1_100M_0/pwm_test_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_test_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==pwm_test_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/pwm_test/ip/pwm_test_pwm_axi_v1_0_0_1/pwm_test_pwm_axi_v1_0_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_test_pwm_axi_v1_0_0_1 || ORIG_REF_NAME==pwm_test_pwm_axi_v1_0_0_1} -quiet] -quiet

# XDC: d:/vivado_pj/pwm_my_ip/pwm_my_ip.gen/sources_1/bd/pwm_test/pwm_test_ooc.xdc
