# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/read_ip_xdc.xdc

# Block Designs: bd/design_12/design_12.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_12 || ORIG_REF_NAME==design_12} -quiet] -quiet

# IP: bd/design_12/ip/design_12_top_fndcontrol2_0_0/design_12_top_fndcontrol2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_12_top_fndcontrol2_0_0 || ORIG_REF_NAME==design_12_top_fndcontrol2_0_0} -quiet] -quiet

# IP: bd/design_12/ip/design_12_clk_wiz_0/design_12_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_12_clk_wiz_0 || ORIG_REF_NAME==design_12_clk_wiz_0} -quiet] -quiet

# IP: bd/design_12/ip/design_12_rst_clk_wiz_100M_0/design_12_rst_clk_wiz_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_12_rst_clk_wiz_100M_0 || ORIG_REF_NAME==design_12_rst_clk_wiz_100M_0} -quiet] -quiet

# XDC: d:/AIOT/vivado_pj/read_ip_pj/read_ip_pj.gen/sources_1/bd/design_12/design_12_ooc.xdc
