# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/vivado_pj/project_mb1/project_mb1.srcs/sources_1/bd/mb1_block/ip/mb1_block_lmb_bram_0/mb1_block_lmb_bram_0.xci
# IP: The module: 'mb1_block_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_pj/project_mb1/project_mb1.gen/sources_1/bd/mb1_block/ip/mb1_block_lmb_bram_0/mb1_block_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb1_block_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/vivado_pj/project_mb1/project_mb1.srcs/sources_1/bd/mb1_block/ip/mb1_block_lmb_bram_0/mb1_block_lmb_bram_0.xci
# IP: The module: 'mb1_block_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_pj/project_mb1/project_mb1.gen/sources_1/bd/mb1_block/ip/mb1_block_lmb_bram_0/mb1_block_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb1_block_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
