# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/vivado_pj/text_lcd_ip_pj/text_lcd_ip_pj.srcs/sources_1/bd/lcd_test/ip/lcd_test_clk_wiz_1_0/lcd_test_clk_wiz_1_0.xci
# IP: The module: 'lcd_test_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_pj/text_lcd_ip_pj/text_lcd_ip_pj.gen/sources_1/bd/lcd_test/ip/lcd_test_clk_wiz_1_0/lcd_test_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lcd_test_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/vivado_pj/text_lcd_ip_pj/text_lcd_ip_pj.gen/sources_1/bd/lcd_test/ip/lcd_test_clk_wiz_1_0/lcd_test_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lcd_test_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/vivado_pj/text_lcd_ip_pj/text_lcd_ip_pj.gen/sources_1/bd/lcd_test/ip/lcd_test_clk_wiz_1_0/lcd_test_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lcd_test_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/vivado_pj/text_lcd_ip_pj/text_lcd_ip_pj.srcs/sources_1/bd/lcd_test/ip/lcd_test_clk_wiz_1_0/lcd_test_clk_wiz_1_0.xci
# IP: The module: 'lcd_test_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_pj/text_lcd_ip_pj/text_lcd_ip_pj.gen/sources_1/bd/lcd_test/ip/lcd_test_clk_wiz_1_0/lcd_test_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lcd_test_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/vivado_pj/text_lcd_ip_pj/text_lcd_ip_pj.gen/sources_1/bd/lcd_test/ip/lcd_test_clk_wiz_1_0/lcd_test_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lcd_test_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/vivado_pj/text_lcd_ip_pj/text_lcd_ip_pj.gen/sources_1/bd/lcd_test/ip/lcd_test_clk_wiz_1_0/lcd_test_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lcd_test_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
