# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/vivado_pj/myip_axi_led/myip_axi_led.srcs/sources_1/bd/axi_led/ip/axi_led_mdm_1_0/axi_led_mdm_1_0.xci
# IP: The module: 'axi_led_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_pj/myip_axi_led/myip_axi_led.gen/sources_1/bd/axi_led/ip/axi_led_mdm_1_0/axi_led_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_led_mdm_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/vivado_pj/myip_axi_led/myip_axi_led.gen/sources_1/bd/axi_led/ip/axi_led_mdm_1_0/axi_led_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_led_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/vivado_pj/myip_axi_led/myip_axi_led.srcs/sources_1/bd/axi_led/ip/axi_led_mdm_1_0/axi_led_mdm_1_0.xci
# IP: The module: 'axi_led_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_pj/myip_axi_led/myip_axi_led.gen/sources_1/bd/axi_led/ip/axi_led_mdm_1_0/axi_led_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_led_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/vivado_pj/myip_axi_led/myip_axi_led.gen/sources_1/bd/axi_led/ip/axi_led_mdm_1_0/axi_led_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_led_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
