# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/AIOT/vivado_pj/dual_port_ram_ip/dual_port_ram_ip.srcs/sources_1/ip/sdpram2/sdpram2.xci
# IP: The module: 'sdpram2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/AIOT/vivado_pj/dual_port_ram_ip/dual_port_ram_ip.gen/sources_1/ip/sdpram2/sdpram2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sdpram2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/AIOT/vivado_pj/dual_port_ram_ip/dual_port_ram_ip.srcs/sources_1/ip/sdpram2/sdpram2.xci
# IP: The module: 'sdpram2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/AIOT/vivado_pj/dual_port_ram_ip/dual_port_ram_ip.gen/sources_1/ip/sdpram2/sdpram2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sdpram2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
