# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/axi_led.xdc

# Block Designs: bd/axi_led/axi_led.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_led || ORIG_REF_NAME==axi_led} -quiet] -quiet

# IP: bd/axi_led/ip/axi_led_microblaze_0_0/axi_led_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_led_microblaze_0_0 || ORIG_REF_NAME==axi_led_microblaze_0_0} -quiet] -quiet

# IP: bd/axi_led/ip/axi_led_axi_uartlite_0_0/axi_led_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_led_axi_uartlite_0_0 || ORIG_REF_NAME==axi_led_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/axi_led/ip/axi_led_dlmb_v10_0/axi_led_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_led_dlmb_v10_0 || ORIG_REF_NAME==axi_led_dlmb_v10_0} -quiet] -quiet

# IP: bd/axi_led/ip/axi_led_ilmb_v10_0/axi_led_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_led_ilmb_v10_0 || ORIG_REF_NAME==axi_led_ilmb_v10_0} -quiet] -quiet

# IP: bd/axi_led/ip/axi_led_dlmb_bram_if_cntlr_0/axi_led_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_led_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==axi_led_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/axi_led/ip/axi_led_ilmb_bram_if_cntlr_0/axi_led_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_led_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==axi_led_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/axi_led/ip/axi_led_lmb_bram_0/axi_led_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_led_lmb_bram_0 || ORIG_REF_NAME==axi_led_lmb_bram_0} -quiet] -quiet

# IP: bd/axi_led/ip/axi_led_mdm_1_0/axi_led_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_led_mdm_1_0 || ORIG_REF_NAME==axi_led_mdm_1_0} -quiet] -quiet

# IP: bd/axi_led/ip/axi_led_clk_wiz_1_0/axi_led_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_led_clk_wiz_1_0 || ORIG_REF_NAME==axi_led_clk_wiz_1_0} -quiet] -quiet

# IP: bd/axi_led/ip/axi_led_rst_clk_wiz_1_100M_0/axi_led_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_led_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==axi_led_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/axi_led/ip/axi_led_xbar_0/axi_led_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_led_xbar_0 || ORIG_REF_NAME==axi_led_xbar_0} -quiet] -quiet

# IP: bd/axi_led/ip/axi_led_microblaze_0_axi_periph_0/axi_led_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_led_microblaze_0_axi_periph_0 || ORIG_REF_NAME==axi_led_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/axi_led/ip/axi_led_myip_axi_led_v1_0_0_0/axi_led_myip_axi_led_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_led_myip_axi_led_v1_0_0_0 || ORIG_REF_NAME==axi_led_myip_axi_led_v1_0_0_0} -quiet] -quiet

# XDC: d:/vivado_pj/myip_axi_led/myip_axi_led.gen/sources_1/bd/axi_led/axi_led_ooc.xdc
