# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/vivado_pj/my_ip_fnd/my_ip_fnd.srcs/sources_1/bd/axi_fnd/ip/axi_fnd_clk_wiz_1_0/axi_fnd_clk_wiz_1_0.xci
# IP: The module: 'axi_fnd_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_pj/my_ip_fnd/my_ip_fnd.gen/sources_1/bd/axi_fnd/ip/axi_fnd_clk_wiz_1_0/axi_fnd_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_fnd_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/vivado_pj/my_ip_fnd/my_ip_fnd.gen/sources_1/bd/axi_fnd/ip/axi_fnd_clk_wiz_1_0/axi_fnd_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_fnd_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/vivado_pj/my_ip_fnd/my_ip_fnd.gen/sources_1/bd/axi_fnd/ip/axi_fnd_clk_wiz_1_0/axi_fnd_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_fnd_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/vivado_pj/my_ip_fnd/my_ip_fnd.srcs/sources_1/bd/axi_fnd/ip/axi_fnd_clk_wiz_1_0/axi_fnd_clk_wiz_1_0.xci
# IP: The module: 'axi_fnd_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_pj/my_ip_fnd/my_ip_fnd.gen/sources_1/bd/axi_fnd/ip/axi_fnd_clk_wiz_1_0/axi_fnd_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_fnd_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/vivado_pj/my_ip_fnd/my_ip_fnd.gen/sources_1/bd/axi_fnd/ip/axi_fnd_clk_wiz_1_0/axi_fnd_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_fnd_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/vivado_pj/my_ip_fnd/my_ip_fnd.gen/sources_1/bd/axi_fnd/ip/axi_fnd_clk_wiz_1_0/axi_fnd_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_fnd_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
