# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/AIOT/vivado_pj/spi_task_ip/spi_task_ip.srcs/sources_1/bd/spi_task_ip/ip/spi_task_ip_clk_wiz_0/spi_task_ip_clk_wiz_0.xci
# IP: The module: 'spi_task_ip_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/AIOT/vivado_pj/spi_task_ip/spi_task_ip.gen/sources_1/bd/spi_task_ip/ip/spi_task_ip_clk_wiz_0/spi_task_ip_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_task_ip_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/AIOT/vivado_pj/spi_task_ip/spi_task_ip.gen/sources_1/bd/spi_task_ip/ip/spi_task_ip_clk_wiz_0/spi_task_ip_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_task_ip_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/AIOT/vivado_pj/spi_task_ip/spi_task_ip.gen/sources_1/bd/spi_task_ip/ip/spi_task_ip_clk_wiz_0/spi_task_ip_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_task_ip_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/AIOT/vivado_pj/spi_task_ip/spi_task_ip.srcs/sources_1/bd/spi_task_ip/ip/spi_task_ip_clk_wiz_0/spi_task_ip_clk_wiz_0.xci
# IP: The module: 'spi_task_ip_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/AIOT/vivado_pj/spi_task_ip/spi_task_ip.gen/sources_1/bd/spi_task_ip/ip/spi_task_ip_clk_wiz_0/spi_task_ip_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_task_ip_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/AIOT/vivado_pj/spi_task_ip/spi_task_ip.gen/sources_1/bd/spi_task_ip/ip/spi_task_ip_clk_wiz_0/spi_task_ip_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_task_ip_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/AIOT/vivado_pj/spi_task_ip/spi_task_ip.gen/sources_1/bd/spi_task_ip/ip/spi_task_ip_clk_wiz_0/spi_task_ip_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_task_ip_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
