# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/vivado_pj/spi_master_ip/spi_master_ip.srcs/sources_1/bd/spi/ip/spi_clk_wiz_1_2/spi_clk_wiz_1_2.xci
# IP: The module: 'spi_clk_wiz_1_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_pj/spi_master_ip/spi_master_ip.gen/sources_1/bd/spi/ip/spi_clk_wiz_1_2/spi_clk_wiz_1_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/vivado_pj/spi_master_ip/spi_master_ip.gen/sources_1/bd/spi/ip/spi_clk_wiz_1_2/spi_clk_wiz_1_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/vivado_pj/spi_master_ip/spi_master_ip.gen/sources_1/bd/spi/ip/spi_clk_wiz_1_2/spi_clk_wiz_1_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/vivado_pj/spi_master_ip/spi_master_ip.srcs/sources_1/bd/spi/ip/spi_clk_wiz_1_2/spi_clk_wiz_1_2.xci
# IP: The module: 'spi_clk_wiz_1_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_pj/spi_master_ip/spi_master_ip.gen/sources_1/bd/spi/ip/spi_clk_wiz_1_2/spi_clk_wiz_1_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/vivado_pj/spi_master_ip/spi_master_ip.gen/sources_1/bd/spi/ip/spi_clk_wiz_1_2/spi_clk_wiz_1_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/vivado_pj/spi_master_ip/spi_master_ip.gen/sources_1/bd/spi/ip/spi_clk_wiz_1_2/spi_clk_wiz_1_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
