set_property SRC_FILE_INFO {cfile:C:/vivado_pj/uart_test/uart_test.srcs/constrs_1/new/uart_xdc.xdc rfile:../../../uart_test.srcs/constrs_1/new/uart_xdc.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18 [get_ports uart_tx]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B18 [get_ports uart_rx]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
