# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/spi_task_xdc.xdc

# Block Designs: bd/spi_task_ip/spi_task_ip.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_task_ip || ORIG_REF_NAME==spi_task_ip} -quiet] -quiet

# IP: bd/spi_task_ip/ip/spi_task_ip_top_fndcontrol2_0_0/spi_task_ip_top_fndcontrol2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_task_ip_top_fndcontrol2_0_0 || ORIG_REF_NAME==spi_task_ip_top_fndcontrol2_0_0} -quiet] -quiet

# IP: bd/spi_task_ip/ip/spi_task_ip_clk_wiz_0/spi_task_ip_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_task_ip_clk_wiz_0 || ORIG_REF_NAME==spi_task_ip_clk_wiz_0} -quiet] -quiet

# IP: bd/spi_task_ip/ip/spi_task_ip_rst_clk_wiz_100M_0/spi_task_ip_rst_clk_wiz_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_task_ip_rst_clk_wiz_100M_0 || ORIG_REF_NAME==spi_task_ip_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: bd/spi_task_ip/ip/spi_task_ip_reset_inv_0_0/spi_task_ip_reset_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_task_ip_reset_inv_0_0 || ORIG_REF_NAME==spi_task_ip_reset_inv_0_0} -quiet] -quiet

# XDC: d:/AIOT/vivado_pj/spi_task_ip/spi_task_ip.gen/sources_1/bd/spi_task_ip/spi_task_ip_ooc.xdc
