# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/AIOT/vivado_pj/uart_controller_pj/uart_controller_pj.srcs/sources_1/ip/fifo_16x8/fifo_16x8.xci
# IP: The module: 'fifo_16x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/AIOT/vivado_pj/uart_controller_pj/uart_controller_pj.gen/sources_1/ip/fifo_16x8/fifo_16x8.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_16x8'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/AIOT/vivado_pj/uart_controller_pj/uart_controller_pj.gen/sources_1/ip/fifo_16x8/fifo_16x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_16x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/AIOT/vivado_pj/uart_controller_pj/uart_controller_pj.srcs/sources_1/ip/fifo_16x8/fifo_16x8.xci
# IP: The module: 'fifo_16x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/AIOT/vivado_pj/uart_controller_pj/uart_controller_pj.gen/sources_1/ip/fifo_16x8/fifo_16x8.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_16x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/AIOT/vivado_pj/uart_controller_pj/uart_controller_pj.gen/sources_1/ip/fifo_16x8/fifo_16x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_16x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
