# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/RTC_fnd_xdc.xdc

# Block Designs: bd/rtc_fnd_axi/rtc_fnd_axi.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtc_fnd_axi || ORIG_REF_NAME==rtc_fnd_axi} -quiet] -quiet

# IP: bd/rtc_fnd_axi/ip/rtc_fnd_axi_microblaze_0_2/rtc_fnd_axi_microblaze_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtc_fnd_axi_microblaze_0_2 || ORIG_REF_NAME==rtc_fnd_axi_microblaze_0_2} -quiet] -quiet

# IP: bd/rtc_fnd_axi/ip/rtc_fnd_axi_axi_uartlite_0_2/rtc_fnd_axi_axi_uartlite_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtc_fnd_axi_axi_uartlite_0_2 || ORIG_REF_NAME==rtc_fnd_axi_axi_uartlite_0_2} -quiet] -quiet

# IP: bd/rtc_fnd_axi/ip/rtc_fnd_axi_axi_fnd_v1_0_0_3/rtc_fnd_axi_axi_fnd_v1_0_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtc_fnd_axi_axi_fnd_v1_0_0_3 || ORIG_REF_NAME==rtc_fnd_axi_axi_fnd_v1_0_0_3} -quiet] -quiet

# IP: bd/rtc_fnd_axi/ip/rtc_fnd_axi_dlmb_v10_2/rtc_fnd_axi_dlmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtc_fnd_axi_dlmb_v10_2 || ORIG_REF_NAME==rtc_fnd_axi_dlmb_v10_2} -quiet] -quiet

# IP: bd/rtc_fnd_axi/ip/rtc_fnd_axi_ilmb_v10_2/rtc_fnd_axi_ilmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtc_fnd_axi_ilmb_v10_2 || ORIG_REF_NAME==rtc_fnd_axi_ilmb_v10_2} -quiet] -quiet

# IP: bd/rtc_fnd_axi/ip/rtc_fnd_axi_dlmb_bram_if_cntlr_2/rtc_fnd_axi_dlmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtc_fnd_axi_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==rtc_fnd_axi_dlmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/rtc_fnd_axi/ip/rtc_fnd_axi_ilmb_bram_if_cntlr_2/rtc_fnd_axi_ilmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtc_fnd_axi_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==rtc_fnd_axi_ilmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/rtc_fnd_axi/ip/rtc_fnd_axi_lmb_bram_2/rtc_fnd_axi_lmb_bram_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtc_fnd_axi_lmb_bram_2 || ORIG_REF_NAME==rtc_fnd_axi_lmb_bram_2} -quiet] -quiet

# IP: bd/rtc_fnd_axi/ip/rtc_fnd_axi_mdm_1_2/rtc_fnd_axi_mdm_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtc_fnd_axi_mdm_1_2 || ORIG_REF_NAME==rtc_fnd_axi_mdm_1_2} -quiet] -quiet

# IP: bd/rtc_fnd_axi/ip/rtc_fnd_axi_clk_wiz_1_2/rtc_fnd_axi_clk_wiz_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtc_fnd_axi_clk_wiz_1_2 || ORIG_REF_NAME==rtc_fnd_axi_clk_wiz_1_2} -quiet] -quiet

# IP: bd/rtc_fnd_axi/ip/rtc_fnd_axi_rst_clk_wiz_1_100M_2/rtc_fnd_axi_rst_clk_wiz_1_100M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtc_fnd_axi_rst_clk_wiz_1_100M_2 || ORIG_REF_NAME==rtc_fnd_axi_rst_clk_wiz_1_100M_2} -quiet] -quiet

# IP: bd/rtc_fnd_axi/ip/rtc_fnd_axi_xbar_2/rtc_fnd_axi_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtc_fnd_axi_xbar_2 || ORIG_REF_NAME==rtc_fnd_axi_xbar_2} -quiet] -quiet

# IP: bd/rtc_fnd_axi/ip/rtc_fnd_axi_microblaze_0_axi_periph_2/rtc_fnd_axi_microblaze_0_axi_periph_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtc_fnd_axi_microblaze_0_axi_periph_2 || ORIG_REF_NAME==rtc_fnd_axi_microblaze_0_axi_periph_2} -quiet] -quiet

# IP: bd/rtc_fnd_axi/ip/rtc_fnd_axi_rtc_axi_v1_0_0_7/rtc_fnd_axi_rtc_axi_v1_0_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtc_fnd_axi_rtc_axi_v1_0_0_7 || ORIG_REF_NAME==rtc_fnd_axi_rtc_axi_v1_0_0_7} -quiet] -quiet

# XDC: d:/vivado_pj/RTC_FND_AXI/RTC_FND_AXI.gen/sources_1/bd/rtc_fnd_axi/rtc_fnd_axi_ooc.xdc
